---
version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ~/mongo_data:/data/db
    depends_on:
      - mongo-ui

  mongo-ui:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    ports:
      - 127.0.0.1:8081:8081
